### PR TITLE
lazy 1.20.2 port

### PR DESCRIPTION
**Pull request by sakura-ryoko**
Hey I am just offering a lazy port for you're mod for 1.20.2,  I hope it works out.

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
Anybody who needs 1.20.2 support faster can clone my temporary fork I suppose ...

**Comment by sakura-ryoko** [comment]
FYI, my QOL fork is nearly ready, I'll resubmit my pull request for it soon.  I just need to test a few things.

**Comment by toydotgame** [comment]
I noticed you archived your fork 2 days ago; is this PR abandoned/does the lazy hotfix still work? I wanna update my server but this is one of the only mods that isn't up-to-date, so I'd like to use it.

**Comment by toydotgame** [comment]
Oh I completely didn't notice that it was under a new name. I've become blind to the trillion names this mod has had (AfkTape -> AfkDisplay -> AfkDisplay (but fork) -> AfkPlus) and I didn't bother searching for anything under a new name sorry lol.

**Pull request closed without merging**
